
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author COMPUTER
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    
    private Connection conn;
    
    public FrmMain(Connection conn) {
        this.conn = conn;
        initComponents();
            noFaktur();
        setLocationRelativeTo(null);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNoFaktur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dtcDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        btnSearchItem = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPPN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtDisc = new javax.swing.JTextField();
        btnCode = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtAllTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniPurchase1 = new javax.swing.JMenuItem();
        mniDiscCode = new javax.swing.JMenuItem();
        mniKodeAkun = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        mnuInput = new javax.swing.JMenu();
        mniCustomer = new javax.swing.JMenuItem();
        mniSupplier = new javax.swing.JMenuItem();
        mniItems = new javax.swing.JMenuItem();
        mnuData = new javax.swing.JMenu();
        mniPurchase2 = new javax.swing.JMenuItem();
        mniSales = new javax.swing.JMenuItem();
        mniStock = new javax.swing.JMenuItem();
        mnuAccounting = new javax.swing.JMenu();
        mniJurnal = new javax.swing.JMenuItem();
        mniGL = new javax.swing.JMenuItem();
        mniTrialBalance = new javax.swing.JMenuItem();
        mniInventoryValue = new javax.swing.JMenuItem();
        mniProfitLoss = new javax.swing.JMenuItem();
        mniBalanceSheet = new javax.swing.JMenuItem();
        Settings = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaction");

        jLabel2.setText("No. Faktur : ");

        txtNoFaktur.setEnabled(false);
        txtNoFaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoFakturActionPerformed(evt);
            }
        });

        jLabel3.setText("Date : ");

        jLabel4.setText("Name : ");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel5.setText("Qty");

        jLabel6.setText("Item");

        txtItem.setEnabled(false);

        btnSearchItem.setText("Search Item");
        btnSearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchItemActionPerformed(evt);
            }
        });

        jLabel7.setText("Price");

        jLabel8.setText("Total");

        txtTotal.setEnabled(false);

        jLabel9.setText("PPN");

        txtPPN.setEnabled(false);

        jLabel10.setText("Sub Total");

        txtSubTotal.setEnabled(false);

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Qty", "Item", "Total", "PPN", "Sub Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMain.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblMain);
        tblMain.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel11.setText("Disc");

        txtDisc.setEnabled(false);

        btnCode.setText("Code");
        btnCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtAllTotal.setEnabled(false);

        jLabel1.setText("Grand Total");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        mnuFile.setText("File");

        mniPurchase1.setText("Purchase");
        mniPurchase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPurchase1ActionPerformed(evt);
            }
        });
        mnuFile.add(mniPurchase1);

        mniDiscCode.setText("Disc Code");
        mniDiscCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiscCodeActionPerformed(evt);
            }
        });
        mnuFile.add(mniDiscCode);

        mniKodeAkun.setText("Akun Code");
        mniKodeAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKodeAkunActionPerformed(evt);
            }
        });
        mnuFile.add(mniKodeAkun);
        mnuFile.add(jSeparator1);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        jMenuBar1.add(mnuFile);

        mnuInput.setText("Input");

        mniCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        mniCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bullet_user.png"))); // NOI18N
        mniCustomer.setText("Customer");
        mniCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCustomerActionPerformed(evt);
            }
        });
        mnuInput.add(mniCustomer);

        mniSupplier.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mniSupplier.setText("Supplier");
        mniSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSupplierActionPerformed(evt);
            }
        });
        mnuInput.add(mniSupplier);

        mniItems.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        mniItems.setText("Item");
        mnuInput.add(mniItems);

        jMenuBar1.add(mnuInput);

        mnuData.setText("Data");

        mniPurchase2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mniPurchase2.setText("Purchase Data");
        mniPurchase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPurchase2ActionPerformed(evt);
            }
        });
        mnuData.add(mniPurchase2);

        mniSales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mniSales.setText("Sales Data");
        mniSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalesActionPerformed(evt);
            }
        });
        mnuData.add(mniSales);

        mniStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mniStock.setText("Stock Data");
        mnuData.add(mniStock);

        jMenuBar1.add(mnuData);

        mnuAccounting.setText("Akuntansi");

        mniJurnal.setText("Jurnal");
        mniJurnal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniJurnalActionPerformed(evt);
            }
        });
        mnuAccounting.add(mniJurnal);

        mniGL.setText("GL");
        mniGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGLActionPerformed(evt);
            }
        });
        mnuAccounting.add(mniGL);

        mniTrialBalance.setText("Trial Balance");
        mniTrialBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTrialBalanceActionPerformed(evt);
            }
        });
        mnuAccounting.add(mniTrialBalance);

        mniInventoryValue.setText("Inventory Value");
        mniInventoryValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInventoryValueActionPerformed(evt);
            }
        });
        mnuAccounting.add(mniInventoryValue);

        mniProfitLoss.setText("Profit-Loss");
        mniProfitLoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProfitLossActionPerformed(evt);
            }
        });
        mnuAccounting.add(mniProfitLoss);

        mniBalanceSheet.setText("Balance Sheet");
        mniBalanceSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBalanceSheetActionPerformed(evt);
            }
        });
        mnuAccounting.add(mniBalanceSheet);

        jMenuBar1.add(mnuAccounting);

        Settings.setText("Settings");
        jMenuBar1.add(Settings);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQty, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchItem))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPPN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCode)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAllTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNoFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(dtcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(btnSearchItem)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(btnCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnNew)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAllTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        executeNew();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
//        executeSave();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        executeDelete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        data.dlgCustomer customer = new data.dlgCustomer(this, true, conn);
        customer.setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchItemActionPerformed
        // TODO add your handling code here:
        data.dlgItem item = new data.dlgItem(this, true, conn);
        item.setVisible(true);
    }//GEN-LAST:event_btnSearchItemActionPerformed

    private void btnCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeActionPerformed
        // TODO add your handling code here:
        dlgDisc1 disc1 = new dlgDisc1(this, true, conn);
        disc1.setVisible(true);
    }//GEN-LAST:event_btnCodeActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    private void mniSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalesActionPerformed
        // TODO add your handling code here:
        data1.dlgSalesData sales = new data1.dlgSalesData(this, true);
        sales.setVisible(true);
    }//GEN-LAST:event_mniSalesActionPerformed

    private void mniCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCustomerActionPerformed
        // TODO add your handling code here:
        data.dlgCustomer customer = new data.dlgCustomer(this, true, conn);
        customer.setVisible(true);
    }//GEN-LAST:event_mniCustomerActionPerformed

    private void mniPurchase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPurchase2ActionPerformed
        // TODO add your handling code here:
        data1.dlgPurchaseData purchase = new data1.dlgPurchaseData(this, true);
        purchase.setVisible(true);
    }//GEN-LAST:event_mniPurchase2ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void mniSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSupplierActionPerformed
        // TODO add your handling code here:
        data.dlgSupplier supplier =new data.dlgSupplier(this, true, conn);
        supplier.setVisible(true);
    }//GEN-LAST:event_mniSupplierActionPerformed

    private void mniPurchase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPurchase1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniPurchase1ActionPerformed

    private void mniJurnalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniJurnalActionPerformed
        // TODO add your handling code here:
        akuntansi.frmJurnal jurnal = new akuntansi.frmJurnal();
        jurnal.setVisible(true);
    }//GEN-LAST:event_mniJurnalActionPerformed

    private void mniGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGLActionPerformed
        // TODO add your handling code here:
        akuntansi.frmGL gl = new akuntansi.frmGL();
        gl.setVisible(true);
    }//GEN-LAST:event_mniGLActionPerformed

    private void mniTrialBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTrialBalanceActionPerformed
        // TODO add your handling code here:
        akuntansi.frmTrialBalance trialbalance = new akuntansi.frmTrialBalance();
        trialbalance.setVisible(true);
    }//GEN-LAST:event_mniTrialBalanceActionPerformed

    private void mniInventoryValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInventoryValueActionPerformed
        // TODO add your handling code here:
        akuntansi.frmInventoryValue inventoryvalue = new akuntansi.frmInventoryValue();
        inventoryvalue.setVisible(true);
    }//GEN-LAST:event_mniInventoryValueActionPerformed

    private void mniProfitLossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProfitLossActionPerformed
        // TODO add your handling code here:
        akuntansi.frmProfitLoss profitloss = new akuntansi.frmProfitLoss();
        profitloss.setVisible(true);
    }//GEN-LAST:event_mniProfitLossActionPerformed

    private void mniBalanceSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBalanceSheetActionPerformed
        // TODO add your handling code here:
        akuntansi.frmBalanceSheet balancesheet = new akuntansi.frmBalanceSheet();
        balancesheet.setVisible(true);
    }//GEN-LAST:event_mniBalanceSheetActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // TODO add your handling code here:
        executeLogOut();
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniDiscCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiscCodeActionPerformed
        // TODO add your handling code here:
        dlgDisc2 disc = new dlgDisc2(this, true, conn);
        disc.setVisible(true);
    }//GEN-LAST:event_mniDiscCodeActionPerformed

    private void mniKodeAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKodeAkunActionPerformed
        // TODO add your handling code here:
        dlgAkunCode code = new dlgAkunCode(this, true, conn);
        code.setVisible(true);
    }//GEN-LAST:event_mniKodeAkunActionPerformed

    private void txtNoFakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoFakturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoFakturActionPerformed

    private void executeLogOut() {
        this.setVisible(false);
        DlgLogin.instance.setVisible(true);
    }
    
    private void removeTableData() {
        DefaultTableModel tableModel = (DefaultTableModel) tblMain.getModel();
        tableModel.setRowCount(0);
    }
    
    @Override
    public void dispose() {
        executeExit();
    }
    
    private void executeExit() {
        if (util.Sutil.msq(this, "Are you sure to exit ? ") == 0) {
            System.exit(0);
        } else {

        }
    }
    
    private void executeNew() {
        noFaktur();
        txtName.setText("");
        txtQty.setText("");
        txtItem.setText("");
        txtPrice.setText("");
        txtTotal.setText("");
        txtPPN.setText("");
        txtSubTotal.setText("");
        removeTableData();
    }
    
    private void noFaktur() {
        try {
            String sql = "SELECT max(nofaktur) FROM transaksimaster;";
            Integer lastDataValue = 0;
            PreparedStatement pstatement = conn.prepareStatement(sql);

            ResultSet rs = pstatement.executeQuery();
            if (rs.isBeforeFirst()) { // check is resultset not empty

                while (rs.next()) {
                    lastDataValue = rs.getInt("max(nofaktur)");
                };
                // tableModel.addRow(data);
            } else {
                util.Sutil.msg(this, "Record Empty");
            }
            ++lastDataValue;
            txtNoFaktur.setText(lastDataValue.toString());

            rs.close();
            pstatement.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void executeDelete() {
        deleteDatabase(Integer.parseInt(txtNoFaktur.getText()));
//        loadAllDatabase();
    
    }
    
    private void deleteDatabase(int idtransaksi) {
        try {

            if (conn != null) {
                System.out.println("Connected to DB!\n");

                String sql = "DELETE FROM transaksidetail where "
                        + "idtransaksi = '" + idtransaksi + "' ;";

                PreparedStatement pstatement = conn.prepareStatement(sql);

                pstatement.execute();
                System.out.println("Deleted.");

                pstatement.close();
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Settings;
    private javax.swing.JButton btnCode;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchItem;
    private com.toedter.calendar.JDateChooser dtcDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mniBalanceSheet;
    private javax.swing.JMenuItem mniCustomer;
    private javax.swing.JMenuItem mniDiscCode;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniGL;
    private javax.swing.JMenuItem mniInventoryValue;
    private javax.swing.JMenuItem mniItems;
    private javax.swing.JMenuItem mniJurnal;
    private javax.swing.JMenuItem mniKodeAkun;
    private javax.swing.JMenuItem mniProfitLoss;
    private javax.swing.JMenuItem mniPurchase1;
    private javax.swing.JMenuItem mniPurchase2;
    private javax.swing.JMenuItem mniSales;
    private javax.swing.JMenuItem mniStock;
    private javax.swing.JMenuItem mniSupplier;
    private javax.swing.JMenuItem mniTrialBalance;
    private javax.swing.JMenu mnuAccounting;
    private javax.swing.JMenu mnuData;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuInput;
    private javax.swing.JTable tblMain;
    private javax.swing.JTextField txtAllTotal;
    private javax.swing.JTextField txtDisc;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoFaktur;
    private javax.swing.JTextField txtPPN;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
